# Site settings
title: Bookball
description: > # this means to ignore newlines until "baseurl:"
  Challenge. Book. Play. O Bookball é a melhor maneira de organizar jogos com amigos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bookball.co" # the base hostname & protocol for your site
email: play@bookball.co
copyright: ©2017 Bookball
language: pt
facebook: bookballapp
twitter: bookballapp
instagram: bookballapp
googleplay_link: "https://play.google.com/store/apps/details?id=co.bookball&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1"
appstore_link: "https://itunes.apple.com/us/app/bookball/id982713846?ls=1&mt=8"
manager: "manager.bookball.co"

# Build settings
permalink: pretty
exclude: [bower_components, bower.json, Gruntfile.js, node_modules, sass]
