# Site settings
title: Bookball
description: > # this means to ignore newlines until "baseurl:"
  A melhor maneira de organizar jogos com amigos. Brevemente disponível na App Store.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bookball.co" # the base hostname & protocol for your site
email: play@bookball.co
copyright: ©2015 Bookball
language: pt

# Build settings
source: ./src
destination: ./site
markdown: kramdown
permalink: pretty
exclude: [sass]
